### ISSUE TITLE
App still returning 401 after updating api key

### ISSUE THREAD

**Issue by ratneshnavlakhe** [khushpanchal/NewsApp#2]
![Uploading image.jpg…]()
Hi @khushpanchal  I cloned repo updated api keys but I am still getting 401 response from the api am I missing something please help

**Comment by khushpanchal** [comment]
@ratneshnavlakhe as per news api doc, reason for 401 can be missing or wrong API key, please cross check the api key.
Try hitting the url on web directly. Also have you attach any screenshot, it is not visible

**Comment by ratneshnavlakhe** [comment]
@khushpanchal the api is working with curl request 
Looks like it’s failing because of ssl certification issue I am not sure about the solution have tried adding network security config as well in the app it is not working

**Comment by ratneshnavlakhe** [comment]
Tried debugging it here is the ss
![Uploading image.jpg…]()

**Comment by ratneshnavlakhe** [comment]
It’s working now thanks @khushpanchal
